version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: school_diary_app_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - '.:/myapp'
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:




# # docker-compose.yml
# version: '3'
# services:
#   db:
#     image: mysql:8.0
#     volumes:
#       - 'db_data:/var/lib/mysql'
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: myapp_development
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password

#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
#     volumes:
#       - '.:/myapp'
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db

# volumes:
#   db_data:
