version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: school_diary_app_production
      MYSQL_USER: school_diary_app
      MYSQL_PASSWORD: ${SCHOOL_DIARY_APP_DATABASE_PASSWORD}

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake assets:precompile && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - '.:/myapp'
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # - RAILS_ENV=production

volumes:
  db_data:
