default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: school_diary_app
  password: <%= ENV["SCHOOL_DIARY_APP_DATABASE_PASSWORD"] %>
  host: db

development:
  <<: *default
  database: school_diary_app_development

test:
  <<: *default
  database: school_diary_app_test

production:
  <<: *default
  database: school_diary_app_production
